In [1]:
import tensorflow as tf
import numpy as np
import random 
import matplotlib.pyplot as plt


In [2]:
SEED_VALUE = 42

#fix random number of seeds
random.seed(SEED_VALUE)
np.random.seed(SEED_VALUE)
tf.random.set_seed(SEED_VALUE)


# Tensorflow Constant and variable

In [4]:
rank0_tensor = tf.constant(3)
print(rank0_tensor)

rank0_tensor = tf.constant(3.141592654)
print(rank0_tensor)

rank0_tensor = tf.constant(3.141592654, dtype=tf.float64)
print(rank0_tensor)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(3.1415927, shape=(), dtype=float32)
tf.Tensor(3.141592654, shape=(), dtype=float64)


In [5]:
#CREATE A RANK-1 constant in tensorflow
rank_1_tensor = tf.constant([2.0, 4.0, 6.0])
print(rank_1_tensor)

tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32)


In [6]:
#You can also explicity define the datatype while creating the tensor
rank_2_tensor = tf.constant([[1,2],
                             [3,4],
                             [5,6]], dtype=tf.int32)
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [7]:
#Create two constant tensors
t1 = tf.constant([[1,2,3],[4,5,6]])
t2 = tf.constant([[7,8,9],[10,11,12]])

print(t1)
print('\n')
print(t2)
print('\n')

#Convatenate tensors along axis =0
print(tf.concat([t1, t2], axis=0))
print('\n')

#Concatenate tensors along axis =1
print(tf.concat([t1,t2], axis=1))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [8]:
# THE unique thing about the tensorflow is that it is used in the deep learning for using ndimenstional multiplication, divison, subtract,addition and more assigned operator functions
# the = operator is used to assigna a new valie to a variable, youy must use the assign() method as shon as below

In [9]:
# create a tensor variable

tensor = tf.Variable([2,4])

# Attempt to assign a new value to the 0th tensor element
try:
    tensor[0]=11
    print('Tensor: ', tensor)
except TypeError:
    print("\Error: A tensor object does not support item assingnment")

\Error: A tensor object does not support item assingnment


In [10]:
# You must use the assign() method to assign a new value to a tensofrlow variable
tensor[0].assign(42)
print(tensor[0])
print(tensor[1])

tf.Tensor(42, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [11]:
# So what is tf.Variable? you can think of it as a wrappper around a tensor whose value can be changed by running operations on it.

In [32]:
#Create some data
x=10*tf.random.uniform(shape=[3,5])
print(x)

#Compute the following quantities for allaxes
xmin = tf.reduce_min(x)
xmax = tf.reduce_max(x)
xmean = tf.reduce_mean(x)
xsum = tf.reduce_sum(x)

print('\nComputed over all axes:\n')
print('min: ', xmin)
print('max: ', xmax)
print('xmean: ', xmean)
print('sum: ', xsum)

#Compute the quantities for axis =1
xmin = tf.reduce_min (x, axis=1)
xmax = tf.reduce_max (x, axis=1)
xmean = tf.reduce_mean (x, axis=1)
xsum = tf.reduce_sum (x, axis=1)


tf.Tensor(
[[1.4241445 4.016162  3.3360183 6.816542  6.908702 ]
 [2.2069418 6.1336193 9.588975  3.314948  2.8096783]
 [5.807008  1.739465  9.826159  9.146085  7.685435 ]], shape=(3, 5), dtype=float32)

Computed over all axes:

min:  tf.Tensor(1.4241445, shape=(), dtype=float32)
max:  tf.Tensor(9.826159, shape=(), dtype=float32)
xmean:  tf.Tensor(5.3839927, shape=(), dtype=float32)
sum:  tf.Tensor(80.75989, shape=(), dtype=float32)


In [42]:
# Create some data.
num_data = 24
data = np.random.uniform(0, 10, num_data)
print('data: \n', data)
print('\n')

#Crete an array of random indices
indices = np.random.choice(data.shape[0], 5, replace=False)
print('indices:', indices)
print('\n')

selected_data = data[indices]

print('selected_data: ', selected_data)

data: 
 [1.07891427 0.31429186 6.36410411 3.14355981 5.08570691 9.07566474
 2.49292229 4.10382923 7.55551139 2.28798165 0.7697991  2.89751453
 1.61221287 9.29697652 8.0812038  6.33403757 8.7146059  8.03672077
 1.86570059 8.92558998 5.39342242 8.07440155 8.960913   3.18003475]


indices: [13  1 20  3 11]


selected_data:  [9.29697652 0.31429186 5.39342242 3.14355981 2.89751453]


In [50]:
# Create some data.
num_data = 24
data = tf.random.uniform(shape=[num_data])
print('data: \n', data)
print('\n')

indices = tf.random.uniform([5], minval=0, maxval=len(data)-1, dtype=tf.dtypes.int32)
print('indices:', indices)
print('\n')

#USE GATHER() method to index one tensoe by aanother tensor
selected_data = tf.gather(data, indices)
print('selected_data:', selected_data)

data: 
 tf.Tensor(
[0.9198024  0.9021473  0.41526616 0.08292842 0.10040832 0.06153822
 0.7671492  0.05545342 0.13344252 0.874243   0.12639618 0.07750273
 0.8898996  0.8573204  0.40581453 0.05270422 0.8703762  0.39350355
 0.41915298 0.32164288 0.8265872  0.5453614  0.64476144 0.95184267], shape=(24,), dtype=float32)


indices: tf.Tensor([ 8  9  9 18  7], shape=(5,), dtype=int32)


selected_data: tf.Tensor([0.13344252 0.874243   0.874243   0.41915298 0.05545342], shape=(5,), dtype=float32)


In [64]:
# Create a random tensor.
tensor = tf.random.normal(shape=[5, 3])
print(tensor)
print('\n')

# Create a tensor with indices.
rows = tf.constant([0, 2, 4])
cols = tf.constant([0, 2])
print('1st, 3rd, and 5th rows:')


# Access specific rows of a tensor by specifying the 
# indices of the rows along with the row axis.
print(tf.gather(tensor, rows, axis=0))
print('\n')
print('1st and 3rd, cols:')

# Access specific cols of a tensor by specifying the 
# indices of the cols along with the col axis.
print(tf.gather(tensor, cols, axis=1))

tf.Tensor(
[[-0.34223905 -0.5263015   0.4441634 ]
 [-0.11258354  2.249716   -0.06672636]
 [-0.52781147  0.62668514  0.96659875]
 [-0.09376683 -0.37389693 -0.09987012]
 [ 1.0982645  -0.23806235  1.6244484 ]], shape=(5, 3), dtype=float32)


1st, 3rd, and 5th rows:
tf.Tensor(
[[-0.34223905 -0.5263015   0.4441634 ]
 [-0.52781147  0.62668514  0.96659875]
 [ 1.0982645  -0.23806235  1.6244484 ]], shape=(3, 3), dtype=float32)


1st and 3rd, cols:
tf.Tensor(
[[-0.34223905  0.4441634 ]
 [-0.11258354 -0.06672636]
 [-0.52781147  0.96659875]
 [-0.09376683 -0.09987012]
 [ 1.0982645   1.6244484 ]], shape=(5, 2), dtype=float32)


In [68]:
# Create a python list.
python_list = [1, 2]

# Create a NumPy array from the list.
numpy_array = np.array(python_list)

# Create a tensor from list.
tensor_from_list = tf.convert_to_tensor(python_list)

#create a tensor from a Numpy array
tensor_from_array = tf.convert_to_tensor(numpy_array)

array_from_tensor = tensor_from_array.numpy()

print('List:   ', python_list)
print('Array:  ', numpy_array)
print('Tensor: ', tensor_from_list)
print('Tensor: ', tensor_from_array)
print('Array:  ', array_from_tensor)

List:    [1, 2]
Array:   [1 2]
Tensor:  tf.Tensor([1 2], shape=(2,), dtype=int32)
Tensor:  tf.Tensor([1 2], shape=(2,), dtype=int32)
Array:   [1 2]
