# 1 Element-Wise Operations

In [21]:
def array_info(arr):
    print("Array shape:", arr.shape)
    print("Array dtype:", arr.dtype)
    print("Array size:", arr.size)
    print("Array data:\n", arr)

In [22]:
import numpy as np
a = np.random.random((4,4))
b = np.random.random((4,4))

print("A", a)
print("B", b)
array_info(a)


A [[0.7036399  0.44531073 0.8232516  0.85745581]
 [0.22913663 0.93125325 0.52864075 0.42537027]
 [0.76273609 0.27777756 0.73156983 0.9869    ]
 [0.73957009 0.84010762 0.30231385 0.15606913]]
B [[0.75271026 0.47183356 0.02701028 0.72195705]
 [0.81246526 0.5026145  0.29918319 0.83436305]
 [0.54892231 0.41544521 0.55086515 0.43794535]
 [0.1571601  0.71516068 0.8808072  0.49999375]]
Array shape: (4, 4)
Array dtype: float64
Array size: 16
Array data:
 [[0.7036399  0.44531073 0.8232516  0.85745581]
 [0.22913663 0.93125325 0.52864075 0.42537027]
 [0.76273609 0.27777756 0.73156983 0.9869    ]
 [0.73957009 0.84010762 0.30231385 0.15606913]]


# 1.1 Element-Wise Scalar Operations
Scalar Addition

In [8]:
a + 5

array([[5.63029359, 5.35087035, 5.2963661 , 5.67240073],
       [5.64533294, 5.17347678, 5.73493675, 5.22992167],
       [5.70408265, 5.7377768 , 5.03427299, 5.54956346],
       [5.61638038, 5.20343606, 5.5885143 , 5.15492121]])

# Scalar Subtraction

In [9]:
a - 5 # Element wise scalar subtraction.

array([[-4.36970641, -4.64912965, -4.7036339 , -4.32759927],
       [-4.35466706, -4.82652322, -4.26506325, -4.77007833],
       [-4.29591735, -4.2622232 , -4.96572701, -4.45043654],
       [-4.38361962, -4.79656394, -4.4114857 , -4.84507879]])

# Scalar Multiplication

In [10]:
a * 10 # Element wise scalar multiplication.

array([[6.30293589, 3.50870348, 2.96366102, 6.72400734],
       [6.4533294 , 1.7347678 , 7.34936747, 2.29921669],
       [7.04082655, 7.37776795, 0.34272988, 5.49563465],
       [6.16380385, 2.03436063, 5.88514298, 1.54921213]])

# Scalar Division

In [11]:
a/10 # Element wise scalar division.

array([[0.06302936, 0.03508703, 0.02963661, 0.06724007],
       [0.06453329, 0.01734768, 0.07349367, 0.02299217],
       [0.07040827, 0.07377768, 0.0034273 , 0.05495635],
       [0.06163804, 0.02034361, 0.05885143, 0.01549212]])

# 1.2 Element-Wise Array Operations
Array Addition

In [12]:
a + b # Element wise array/vector addition.

array([[1.36568947, 0.68176522, 0.44548468, 1.58193272],
       [0.9043652 , 0.94303608, 0.83068685, 0.69889832],
       [0.76423353, 0.8416446 , 0.75891197, 0.58056842],
       [0.67221322, 0.79285936, 1.35014982, 1.14789106]])

# Array Subtraction

In [13]:
a - b # Element wise array/vector subtraction.

array([[-0.1051023 ,  0.01997548,  0.14724753, -0.23713125],
       [ 0.38630067, -0.59608253,  0.63918665, -0.23905499],
       [ 0.64393178,  0.63390899, -0.69036599,  0.51855851],
       [ 0.56054755, -0.38598723, -0.17312123, -0.83804863]])

# Array Multiplication

In [14]:
a * b # Element wise array/vector multiplication.

array([[0.46351531, 0.1161012 , 0.04419369, 0.61156998],
       [0.16716205, 0.13350067, 0.07037027, 0.10782789],
       [0.04235119, 0.07663126, 0.02483554, 0.01703919],
       [0.03441427, 0.11990995, 0.4482334 , 0.15383209]])

# Array Division

In [15]:
a / b # element wise array/vector division

array([[ 0.85708066,  1.06036805,  1.98745259,  0.73928212],
       [ 2.49132261,  0.22542354,  7.67557158,  0.4902625 ],
       [11.70527725,  7.10303645,  0.04729664, 17.72501843],
       [11.03974667,  0.34514426,  0.77269807,  0.15601804]])

In [25]:
print('Array "a":')
array_info(a)
print('Array "c":')
c = np.random.rand(2, 4)
array_info(c)

import traceback
try:
    a + c
except Exception:
    traceback.print_exc()


Array "a":
Array shape: (4, 4)
Array dtype: float64
Array size: 16
Array data:
 [[0.7036399  0.44531073 0.8232516  0.85745581]
 [0.22913663 0.93125325 0.52864075 0.42537027]
 [0.76273609 0.27777756 0.73156983 0.9869    ]
 [0.73957009 0.84010762 0.30231385 0.15606913]]
Array "c":
Array shape: (2, 4)
Array dtype: float64
Array size: 8
Array data:
 [[0.27801002 0.63926699 0.95235031 0.48405405]
 [0.27291143 0.32568777 0.61379554 0.48004025]]


Traceback (most recent call last):
  File "C:\Users\nihar\AppData\Local\Temp\ipykernel_36116\3148026610.py", line 9, in <module>
    a + c
    ~~^~~
ValueError: operands could not be broadcast together with shapes (4,4) (2,4) 


# Broadcasting

There is a concept of broadcasting in NumPy, which tries to copy rows or columns in the lower-dimensional array to make an equal dimensional array of higher-dimensional array.

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e., rightmost) dimensions and works its way left. Two dimensions are compatible when:

They are equal, or
One of them is 1
The examples below show how B is successfully broadcasted to A according to the rules above.

A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5


In [27]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
b = np.array([0, 1, 0])

print('Array "a":')
array_info(a)
print('Array "b":')
array_info(b)

print('Array "a+b":')
array_info(a+b)

Array "a":
Array shape: (3, 3)
Array dtype: int32
Array size: 9
Array data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array "b":
Array shape: (3,)
Array dtype: int32
Array size: 3
Array data:
 [0 1 0]
Array "a+b":
Array shape: (3, 3)
Array dtype: int32
Array size: 9
Array data:
 [[1 3 3]
 [4 6 6]
 [7 9 9]]


# Linear Algebra
Transpose
Either syntax below can be used:

result = np.transpose(a, axes=None)

result = a.transpose(*axes)

result = a.T
Returns a view of the NumPy array a with axes transposed.

In [30]:
a = np.random.random((2,3))
print('Array "a":')
array_info(a)

print('tranpose of a:')
a_transpose = a.transpose() # or a.T
array_info(a_transpose)

Array "a":
Array shape: (2, 3)
Array dtype: float64
Array size: 6
Array data:
 [[0.17156344 0.87156507 0.11770348]
 [0.39395166 0.6056029  0.59462406]]
tranpose of a:
Array shape: (3, 2)
Array dtype: float64
Array size: 6
Array data:
 [[0.17156344 0.39395166]
 [0.87156507 0.6056029 ]
 [0.11770348 0.59462406]]


# Matrix Multiplication
two ways of performing matrix multiplication.

np.matmul
Python @ operator

Using matmul is the most common approach for multiplying two matrices using Numpy. Multiplying two matrices requires that the number of columns of the first matrix, M, equals the number of rows in the second matrix, N, as shown below.

M        N      
[p, q] x [q, r] = [p , r]

In [32]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)
c = np.matmul(a,b)
print("matrixmultiplication:")
array_info(c)

print('{} x {} --> {}'.format(a.shape, b.shape, c.shape))

Array "a":
Array shape: (3, 4)
Array dtype: float64
Array size: 12
Array data:
 [[0.71337664 0.37763139 0.82232775 0.5989631 ]
 [0.80500373 0.34168007 0.03922475 0.22072105]
 [0.71397599 0.96027163 0.42817184 0.14372091]]
Array "b"
Array shape: (4, 2)
Array dtype: float64
Array size: 8
Array data:
 [[0.01043611 0.86652095]
 [0.74020204 0.72135705]
 [0.69297781 0.2900908 ]
 [0.74913687 0.35210345]]
matrixmultiplication:
Array shape: (3, 2)
Array dtype: float64
Array size: 6
Array data:
 [[1.30552863 1.34000956]
 [0.45384555 1.0331213 ]
 [1.12262637 1.4861872 ]]
(3, 4) x (4, 2) --> (3, 2)


# Using: `@` operator

In [33]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

# Matrix multiplication of a and b.
c = a@b 
array_info(c)

Array "a":
Array shape: (3, 4)
Array dtype: float64
Array size: 12
Array data:
 [[0.23081758 0.10935692 0.01280249 0.62260165]
 [0.19769048 0.96340999 0.82258253 0.52935719]
 [0.68503071 0.80545311 0.15204162 0.24546995]]
Array "b"
Array shape: (4, 2)
Array dtype: float64
Array size: 8
Array data:
 [[0.69517659 0.02883649]
 [0.72364156 0.6534426 ]
 [0.80243403 0.56721342]
 [0.98680013 0.89446346]]
Array shape: (3, 2)
Array dtype: float64
Array size: 6
Array data:
 [[0.86425074 0.64227061]
 [2.01703126 1.57530434]
 [1.42330981 0.8518752 ]]


# Matrix Inverse
np.linalg.inv(a)
For a square matrix, a, compute the (multiplicative) inverse of a matrix.

In [37]:
A = np.random.random((3,3))
print('Array "A":')
array_info(A)

A_inverse = np.linalg.inv(A)
print("Inverse")
array_info(A_inverse)

print('"A x A_inverse = Identity" should be true:')
A_X_A_inverse = np.matmul(A, A_inverse)  # A x A_inverse = I = Identity matrix
array_info(A_X_A_inverse)


Array "A":
Array shape: (3, 3)
Array dtype: float64
Array size: 9
Array data:
 [[0.55864572 0.66898628 0.8716764 ]
 [0.26229479 0.54742839 0.81479029]
 [0.6374109  0.0836767  0.17591571]]
Inverse
Array shape: (3, 3)
Array dtype: float64
Array size: 9
Array data:
 [[ 0.59510648 -0.9468912   1.4369239 ]
 [10.01387128 -9.67797754 -4.79396128]
 [-6.91953597  8.03441614  2.75832058]]
"A x A_inverse = Identity" should be true:
Array shape: (3, 3)
Array dtype: float64
Array size: 9
Array data:
 [[ 1.00000000e+00  8.88178420e-16 -8.88178420e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16  1.00000000e+00]]


#  Dot Product
The dot product between two euqal length vectors is a scalar defined by the sum of the element-wise product of the two vectors.

np.dot(a, b, out=None)

In [38]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

array_info(a)
array_info(b)

dot_prod = np.dot(a, b) 
array_info(dot_prod)

Array shape: (4,)
Array dtype: int32
Array size: 4
Array data:
 [1 2 3 4]
Array shape: (4,)
Array dtype: int32
Array size: 4
Array data:
 [5 6 7 8]
Array shape: ()
Array dtype: int32
Array size: 1
Array data:
 70


# Array Statistics
3.1 Sum

In [39]:
a = np.array([1, 2, 3, 4, 5])

print(a.sum())

15


# Sum Along Axis

In [40]:
a = np.array([[1, 2, 3], [4, 5, 6]])
array_info(a)
print('')

print('sum along axis=0: ',a.sum(axis = 0)) # Sum along axis=0 ie: 1+4, 2+5, 3+6
print("")
print('sum along axis=1: ',a.sum(axis = 1)) # Sum along axis=1 ie: 1+2+3, 4+5+6

Array shape: (2, 3)
Array dtype: int32
Array size: 6
Array data:
 [[1 2 3]
 [4 5 6]]

sum along axis=0:  [5 7 9]

sum along axis=1:  [ 6 15]


# Minimum and Maximum

In [41]:
a = np.array([-1.1, 2, 5, 100])

print('Minimum = ', a.min())
print('Maximum = ', a.max())

Minimum =  -1.1
Maximum =  100.0


# Min and Max along Axis

In [42]:
a = np.array([[-2, 0, 4], [1, 2, 3]])

array_info(a)

print('a =\n',a,'\n')
print('Minimum = ', a.min())
print('Maximum = ', a.max())
print()
print('Minimum along axis 0 = ', a.min(0))
print('Maximum along axis 0 = ', a.max(0))
print()
print('Minimum along axis 1 = ', a.min(1))
print('Maximum along axis 1 = ', a.max(1))

Array shape: (2, 3)
Array dtype: int32
Array size: 6
Array data:
 [[-2  0  4]
 [ 1  2  3]]
a =
 [[-2  0  4]
 [ 1  2  3]] 

Minimum =  -2
Maximum =  4

Minimum along axis 0 =  [-2  0  3]
Maximum along axis 0 =  [1 2 4]

Minimum along axis 1 =  [-2  1]
Maximum along axis 1 =  [4 3]


# Mean and Standard Deviation

In [43]:
# Create some data.
data = np.array([1.2, 2.3, 5.0, 3.3, 1.4, 5.6])

print('Mean of the array               = {:8.6f}'.format(data.mean()))
print('Standard deviation of the array = {:8.6f}'.format(data.std()))

Mean of the array               = 3.133333
Standard deviation of the array = 1.684900


# Standardizing an Array
Normalize the data array to have mean=0 and std=1.

In [44]:
print('Array              = ', data)
print('Mean               = {:8.6f}'.format(data.mean()))
print('Standard deviation = {:8.6f}'.format(data.std()))
print()

standardized_array = (data - data.mean())/data.std()

print('Standardized Array = ', standardized_array)
print('Mean               = {:8.6f}'.format(standardized_array.mean()))  
print('Standard deviation = {:8.6f}'.format(standardized_array.std()))  

Array              =  [1.2 2.3 5.  3.3 1.4 5.6]
Mean               = 3.133333
Standard deviation = 1.684900

Standardized Array =  [-1.14744675 -0.49458912  1.10787962  0.09891782 -1.02874536  1.46398379]
Mean               = -0.000000
Standard deviation = 1.000000
