# NUMPY[numerical python]

In [1]:
a =3
print(len(dir(a)))
dir(a)[-10:]

73


['as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

In [2]:
points= [[0,1],[10,5],[7,3]]
points

[[0, 1], [10, 5], [7, 3]]

# Random intgeres or random numbers

In [3]:
from random import randint

num_points = 10
x_range = (0, 10)
y_range = (0, 50)
points = [[randint(*x_range), randint(*y_range)] for _ in range(num_points)]
points

[[0, 14],
 [6, 9],
 [4, 10],
 [1, 26],
 [7, 31],
 [7, 26],
 [2, 37],
 [1, 7],
 [6, 17],
 [10, 8]]

In [4]:
import numpy as np
points = np.array(points)
points

array([[ 0, 14],
       [ 6,  9],
       [ 4, 10],
       [ 1, 26],
       [ 7, 31],
       [ 7, 26],
       [ 2, 37],
       [ 1,  7],
       [ 6, 17],
       [10,  8]])

# numpy function randint to create an ndarray of points

In [5]:
import numpy as np
num_dims = 2
num_points = 10
x_range=(0, 11)
y_range=(0, 51)
points = np.random.randint(low=(x_range[0], y_range[0]), high=(x_range[1], y_range[1]), size=(num_points, num_dims))
points

array([[ 1, 15],
       [ 9, 16],
       [ 0, 24],
       [ 4, 27],
       [ 7, 13],
       [ 0, 50],
       [ 2, 18],
       [ 7, 11],
       [ 9, 47],
       [10, 11]])

In [6]:
num_dims = 2
num_points = 100000
x_range = (0,10)
y_range = (0, 50)

# Numpy Basics

In [7]:
#Converting lists to arrays
py_list = [1,2,3,4,5,6,7,8,9,10]
np_array = np.array(py_list)
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
py_list = [[1,2,3], [4,5,6],[7,8,9],[10,11,12]]
np_array = np.array(py_list)
np_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Indexing refers to accessing a particular element of an array and Slicing refers to accessing a segement of an array

In [9]:
print('First row:\t\t\t{}\n'.format(np_array[0]))
print('First row:\t\t\t{}\n'.format(np_array[0,:]))
print('First column:\t\t\t{}\n'.format(np_array[:,0]))
print('3rd row 2nd column element:\t{}\n'.format(np_array[2,1]))
print('2nd row onwards and 2nd column onwards :\n{}\n'.format(np_array[1:, 1:]))
print('Last 2 rows and last 2 columns onwards:\n{}\n'.format(np_array[-2:, -2:]))
print('Array with the 3rd, 1st and 4th row:\n{}\n'.format(np_array[[2,0,3]]))
print('Array with the 1st and 3rd col:\n{}\n'.format(np_array[:,[0,2]]))

First row:			[1 2 3]

First row:			[1 2 3]

First column:			[ 1  4  7 10]

3rd row 2nd column element:	8

2nd row onwards and 2nd column onwards :
[[ 5  6]
 [ 8  9]
 [11 12]]

Last 2 rows and last 2 columns onwards:
[[ 8  9]
 [11 12]]

Array with the 3rd, 1st and 4th row:
[[ 7  8  9]
 [ 1  2  3]
 [10 11 12]]

Array with the 1st and 3rd col:
[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]



# Basic Attributes of Numpy arrays


In [10]:
print('Data type:\t{}'.format(np_array.dtype))
print('Array shape:\t{}'.format(np_array.shape))

Data type:	int32
Array shape:	(4, 3)


# Create a conenience function for printing array formation

In [11]:
def array_info(array):
    print('Array:\n{}'.format(array))
    print('Data type:\t{}'.format(np_array.dtype))
    print('Array shape:\t{}\n'.format(np_array.shape)
    )
array_info(np_array)

Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Data type:	int32
Array shape:	(4, 3)



# Creating Numpy using built in functions and Datatypes

Sequence array wea re creating with np.arange([start,]stop, [step,]dtype=None)

In [12]:
#Sequence array
import numpy as np
array = np.arange(10, dtype=np.int64)
array_info(array)

Array:
[0 1 2 3 4 5 6 7 8 9]
Data type:	int32
Array shape:	(4, 3)



In [13]:
# Sequence array
array = np.arange(5, 10, 2, dtype=np.float32)
array_info(array)

Array:
[5. 7. 9.]
Data type:	int32
Array shape:	(4, 3)



Linspace returns evenly spaced samples, calcuated over the interval [start, stop]. it is defined in this fashion 
np.linspace(start, stop, num=50, endpoint=True, retstep=Flase, dtype=Noine, axis=0)

In [14]:
#linspace
linespace = np.linspace(0,5,7, dtype=np.float32) #7 elements between 0 and 5
array_info(linespace)

Array:
[0.        0.8333333 1.6666666 2.5       3.3333333 4.1666665 5.       ]
Data type:	int32
Array shape:	(4, 3)



# Zeros Array

In [15]:
#Zeros array/matrix
zeros = np.zeros((2,3),dtype=np.float32)
array_info(zeros)


Array:
[[0. 0. 0.]
 [0. 0. 0.]]
Data type:	int32
Array shape:	(4, 3)



# Ones Array

In [16]:
# Ones Array/matrix
ones = np.ones((3,2), dtype=np.int8)
array_info(ones)

Array:
[[1 1]
 [1 1]
 [1 1]]
Data type:	int32
Array shape:	(4, 3)



# Constant_Array

In [17]:
array = np.full((3,3,), 3.14)
array_info(array)

Array:
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]
Data type:	int32
Array shape:	(4, 3)



# Identity array

In [18]:
identity = np.eye(5, dtype=np.float32)
array_info(identity)

Array:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Data type:	int32
Array shape:	(4, 3)



# Random Integers Array
np.random.ranint(low, high=None, size=None, dtype='1')

In [19]:
random_array = np.random.random((5,5))
array_info(random_array)

Array:
[[0.23276409 0.61395715 0.87498986 0.06389589 0.74700248]
 [0.87669898 0.55762322 0.43470405 0.89806169 0.14484838]
 [0.48539968 0.46393688 0.22628864 0.37274456 0.56362313]
 [0.52260716 0.76991589 0.85112275 0.17973985 0.6930655 ]
 [0.63756836 0.59996139 0.55450418 0.75485093 0.22225017]]
Data type:	int32
Array shape:	(4, 3)



# Boolean array

In [20]:
bool_array = random_array>0.5
array_info(bool_array)

Array:
[[False  True  True False  True]
 [ True  True False  True False]
 [False False False False  True]
 [ True  True  True False  True]
 [ True  True  True  True False]]
Data type:	int32
Array shape:	(4, 3)



In [21]:
values = random_array[bool_array]
array_info(values)

Array:
[0.61395715 0.87498986 0.74700248 0.87669898 0.55762322 0.89806169
 0.56362313 0.52260716 0.76991589 0.85112275 0.6930655  0.63756836
 0.59996139 0.55450418 0.75485093]
Data type:	int32
Array shape:	(4, 3)



# Data Tye Conversion

In [22]:
age_in_years = np.random.randint(0,100,10)
array_info(age_in_years)

Array:
[34 37 83 45 13 63 91 10 12 44]
Data type:	int32
Array shape:	(4, 3)



In [24]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com


'DOSKEY' is not recognized as an internal or external command,
operable program or batch file.

[notice] A new release of pip is available: 24.1 -> 24.1.2
[notice] To update, run: C:\Users\nihar\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip


In [26]:
import numpy as np
age_in_years = age_in_years.astype(np.uint8)
array_info(age_in_years)

Array:
[34 37 83 45 13 63 91 10 12 44]
Data type:	int32
Array shape:	(4, 3)



In [27]:
age_in_years=age_in_years.astype(np.float64)
array_info(age_in_years)

Array:
[34. 37. 83. 45. 13. 63. 91. 10. 12. 44.]
Data type:	int32
Array shape:	(4, 3)



# Mathematical Functions
# Exponential functions

In [29]:
array = np.array([np.full(3, -1), np.zeros(3), np.ones(3)])
array_info(array)

print('Exponential of an array:')
exp_array = np.exp(array)
array_info(exp_array)

Array:
[[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]
Data type:	int32
Array shape:	(4, 3)

Exponential of an array:
Array:
[[0.36787944 0.36787944 0.36787944]
 [1.         1.         1.        ]
 [2.71828183 2.71828183 2.71828183]]
Data type:	int32
Array shape:	(4, 3)



# Square root

In [30]:
array = np.arange(10)
array_info(array)

print("Square root:")
root_array = np.sqrt(array)
array_info(root_array)

Array:
[0 1 2 3 4 5 6 7 8 9]
Data type:	int32
Array shape:	(4, 3)

Square root:
Array:
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
Data type:	int32
Array shape:	(4, 3)



# Logrithm

In [32]:
array = np.array([0, np.exp(1), np.exp(1)**2, 1, 10])
array_info(array)

print('Logrithm:')
log_array = np.log(array)
array_info(log_array)

Array:
[ 0.          2.71828183  7.3890561   1.         10.        ]
Data type:	int32
Array shape:	(4, 3)

Logrithm:
Array:
[      -inf 1.         2.         0.         2.30258509]
Data type:	int32
Array shape:	(4, 3)



C:\Users\nihar\AppData\Local\Temp\ipykernel_33060\2352674282.py:5: RuntimeWarning: divide by zero encountered in log
  log_array = np.log(array)


# Power

In [36]:
array = np.arange(0,6, dtype=np.int64)
array_info(array)

print('Power:')
pow_array = np.power(array, 3)
array_info(pow_array)

Array:
[0 1 2 3 4 5]
Data type:	int32
Array shape:	(4, 3)

Power:
Array:
[  0   1   8  27  64 125]
Data type:	int32
Array shape:	(4, 3)



# Clip Values

In [37]:
array = np.random.random((3,3))
array_info(array)

print('Clipped between 0.2 and 0.5')
cliped_array = np.clip(array, 0.2, 0.5)
array_info(cliped_array)

print('Clipped to 0.2')
cliped_array = np.clip(array, 0.2, np.inf)
array_info(cliped_array)

Array:
[[0.24767645 0.37994335 0.30535833]
 [0.98894037 0.94818368 0.49062695]
 [0.91514595 0.87928644 0.67746723]]
Data type:	int32
Array shape:	(4, 3)

Clipped between 0.2 and 0.5
Array:
[[0.24767645 0.37994335 0.30535833]
 [0.5        0.5        0.49062695]
 [0.5        0.5        0.5       ]]
Data type:	int32
Array shape:	(4, 3)

Clipped to 0.2
Array:
[[0.24767645 0.37994335 0.30535833]
 [0.98894037 0.94818368 0.49062695]
 [0.91514595 0.87928644 0.67746723]]
Data type:	int32
Array shape:	(4, 3)

