In [1]:
import numpy as np

def array_info(array):
    print('Array:\n{}'.format(array))
    print('Data type:\t{}'.format(array.dtype))
    print('Array shape:\t{}'.format(array.shape))
    print('Array Dim:\t{}\n'.format(array.ndim))

In [2]:
print('Create a 1D array:')
a = np.arange(1, 13, dtype=int)
array_info(a)
print("a[0] =", a[0])

Create a 1D array:
Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
a[0] = 1


In [5]:
a = a.reshape(1, 12)
array_info(a)

print("a[0] = ", a[0])
print("a[0,5] = ", a[0, 5])

Array:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
a[0] =  [ 1  2  3  4  5  6  7  8  9 10 11 12]
a[0,5] =  6


In [6]:
a=a.reshape(1, -1)
array_info(a)

Array:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [7]:
a = a.reshape(12, 1)
array_info(a)
print("a[0] =", a[0])
print("a[5, 0] =", a[5, 0])

Array:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
a[0] = [1]
a[5, 0] = 6


# Reshaping Multi dimensional arrays

In [10]:
b = np.array([
    [[10,11],[10,12],[10,13],[10,14],[10,15]],
    [[20,21],[20,22],[20,23],[20,24],[20,25]],
    [[30,31],[30,32],[30,33],[30,34],[30,35]],
])

array_info(b)
print("b[0,0:] = ", b[0,0,:])
print("b[0,1:] = ", b[0,1])
print("b[2,0,:] =", b[2,0,:])

Array:
[[[10 11]
  [10 12]
  [10 13]
  [10 14]
  [10 15]]

 [[20 21]
  [20 22]
  [20 23]
  [20 24]
  [20 25]]

 [[30 31]
  [30 32]
  [30 33]
  [30 34]
  [30 35]]]
b[0,0:] =  [10 11]
b[0,1:] =  [10 12]
b[2,0,:] = [30 31]


In [11]:
b = b.reshape(3,10)
array_info(b)

Array:
[[10 11 10 12 10 13 10 14 10 15]
 [20 21 20 22 20 23 20 24 20 25]
 [30 31 30 32 30 33 30 34 30 35]]


# Adding an axis/Dimension

In [13]:
b = np.arange(1, 10, dtype=int)
b = b.reshape(3,3)
array_info(b)
print(b.shape)

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [18]:
b = b.reshape(1,3,3)
array_info(b)

Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


# Expand Dimensions

In [24]:
print('Create a 1D array:')
c = np.arange(1, 10, dtype=int )
array_info(c)

c = c.reshape(3,3)
array_info(c)
# expand dimensions using: np.expand_dims
print('Using np.expand_dims:')
c_expand = np.expand_dims(c, axis=0)
array_info(c_expand)

#expand dimensions using: np.newaxis
print('Using np.newaxis:')
c_newaxis = c[np.newaxis, : , :]
array_info(c_newaxis)

Create a 1D array:
Array:
[1 2 3 4 5 6 7 8 9]
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Using np.expand_dims:
Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Using np.newaxis:
Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


# Squeeze

In [26]:
e = np.arange(1, 10, dtype=int)
e = e.reshape(1,3,3)
array_info(e)

Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [29]:
import traceback

#should get a value error.
print('Squeese along axis=1, should get ValueError')
try:
    e_squeezed_error = np.squeeze(e, axis=1)
except Exception as e:
    traceback.print_exc()

Squeese along axis=1, should get ValueError


Traceback (most recent call last):
  File "C:\Users\nihar\AppData\Local\Temp\ipykernel_30296\2540636352.py", line 6, in <module>
    e_squeezed_error = np.squeeze(e, axis=1)
                                  ^
NameError: name 'e' is not defined


# Reshape Revisit

In [40]:
f = np.arange(10)
array_info(f)

print('Reshape thr aarray as two columns')
f = f.reshape(-3,2)
array_info(f)

Array:
[0 1 2 3 4 5 6 7 8 9]
Reshape thr aarray as two columns
Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# Flattening arrays

In [43]:
# Create three separate 4x4 arrays.
h1 = np.full((4, 4), 1, dtype='float32')
h2 = np.full((4, 4), 2, dtype='float32')
h3 = np.full((4, 4), 3, dtype='float32')

# create a 3x4x4 array
h = np.zeros((3,4,4))
h[0]= h1
h[1]= h2
h[2]= h3

array_info(h)

Array:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]]


In [46]:
h = h.reshape(1,3,16)
array_info(h)

Array:
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
  [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]]]


# Combining Array/MATRICES
# CONCATENATE

In [50]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9]])

array_info(a)
array_info(b)

print('Concatenate along axis zero:')
array = np.concatenate((a1, a2), axis=0)
array_info(array)

Array:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Concatenate along axis zero:
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# horizontal stacking: hstack

In [52]:
a1 = np.array([[1, 1, 1], [2, 2, 2]])
a2 = np.array([[3, 3, 3, 3], [4, 4, 4, 4]])

array_info(a1)
array_info(a2)

a_hstacked = np.hstack((a1, a2))
array_info(a_hstacked)

Array:
[[1 1 1]
 [2 2 2]]
Array:
[[3 3 3 3]
 [4 4 4 4]]
Array:
[[1 1 1 3 3 3 3]
 [2 2 2 4 4 4 4]]


In [53]:
b1 = np.array([[1],[2],[3]])
b2 = np.array([[4],[5],[6]])

array_info(b1)
array_info(b2)

b_hstacked = np.hstack((b1,b2))

print('Horizontal stack:')
array_info(b_hstacked)

Array:
[[1]
 [2]
 [3]]
Array:
[[4]
 [5]
 [6]]
Horizontal stack:
Array:
[[1 4]
 [2 5]
 [3 6]]


#  Vertical Stacking: vstack
# np.vstack(tup)
# Stack arrays in sequence vertically (row-wise).

In [56]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

array_info(a1)
array_info(a2)

a_vstacked = np.vstack((a1, a2))
array_info(a_vstacked)

Array:
[1 2 3]
Array:
[4 5 6]
Array:
[[1 2 3]
 [4 5 6]]


In [57]:
# Create three separate 1x4x4 arrays.
h1 = np.full((1, 4, 4), 1, dtype='float32')
h2 = np.full((1, 4, 4), 2, dtype='float32')
h3 = np.full((1, 4, 4), 3, dtype='float32')

h = np.vstack((h1,h2,h3))
array_info(h)

Array:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]]
